apiVersion: v1
kind: ResourceQuota
metadata:
    name: demo-namespace
spec:
    hard:
      limits.cpu: "4"
      limits.memory: 8Gi
      persistentvolumeclaims: "4"
      pods: "20"
      requests.cpu: "3"
      requests.memory: 7Gi
      requests.storage: 20Gi
      services.loadbalancers: "3"